using Design.ORiN3.Common.V1.AutoGenerated;

namespace GeoLibrary.ORiN3.Provider.AWS.S3;

public enum AWSS3ProviderResultCode
{
    AWSApiExecutionError = ResultCode.ProviderSpecificResultCode + 1,
    ObjectNotFound,
    ObjectNotWritable,
    InvalidCreationOption,
}
