using Design.ORiN3.Common.V1.AutoGenerated;
using ORiN3.Provider.Core.ProviderException;

namespace ORiN3.Provider.AWS.S3;

[Serializable]
public class GeoLibraryProviderException : ProviderCoreException
{
    public GeoLibraryProviderException(GeoLibraryProviderResultCode resultCode, string message)
        : base((ResultCode)resultCode, message)
    {
    }

    public GeoLibraryProviderException(GeoLibraryProviderResultCode resultCode, string message, Exception exception)
        : base((ResultCode)resultCode, message, exception)
    {
    }
}
