using Design.ORiN3.Common.V1.AutoGenerated;
using ORiN3.Provider.Core.ProviderException;

namespace GeoLibrary.ORiN3.Provider.BaseLib;

[Serializable]
public class GeoLibraryProviderException : ProviderCoreException
{
    public GeoLibraryProviderException(GeoLibraryProviderResultCode resultCode, params object[] args)
        : base(resultCode.ToErrorMessage(args), (ResultCode)resultCode)
    {
    }

    public GeoLibraryProviderException(ResultCode resultCode, params object[] args)
        : base(resultCode, args)
    {
    }

    public GeoLibraryProviderException(GeoLibraryProviderResultCode resultCode, string message, Exception exception)
        : base((ResultCode)resultCode, message, exception)
    {
    }
}

[Serializable]
public class GeoLibraryProviderException<T> : ProviderCoreException
    where T : Enum
{
    public GeoLibraryProviderException(T resultCode, string message)
        : base(message, (ResultCode)(object)resultCode)
    {
    }

     public GeoLibraryProviderException(T resultCode, string message, Exception innerException)
        : base((ResultCode)(object)resultCode, message, innerException)
    {
    }
}
