using Design.ORiN3.Common.V1.AutoGenerated;

namespace GeoLibrary.ORiN3.Provider.Azure.Storage;

public enum AzureStorageProviderResultCode
{
    AzureApiExecutionError = ResultCode.ProviderSpecificResultCode + 1,
    BlobNotFound,
    BlobNotWritable,
    InvalidCreationOption,
}
